# Generated by Django 4.1.7 on 2023-03-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='mother',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
